### ISSUE TITLE
Error: No detecta un módulo llamado datetimewidget

### ISSUE THREAD

**Issue by injcristianrojas** [ibachman/seguridad-de-software#1]
Estimadas:

Al intentar correr vuestra aplicación en mi máquina, me entrega el siguiente error:

![screenshot from 2015-05-18 17 03 56](https://cloud.githubusercontent.com/assets/862690/7689106/357314e8-fd80-11e4-88d0-4e0f3ca677fd.png)

Espero lo corrijan a la brevedad.

Saludos cordiales,

**Comment by aibsen** [comment]
Profesor,
Se me olvidó poner en el readme que hay que hacer,

pip install django-datetime-widget

para instalar un widget que usamos. Saludos y disculpe las molestias.

**Comment by injcristianrojas** [comment]
Excelente. Aquí tienes 2 alternativas entonces:
- Incluye el datetime en la parte del pip del README
- O, mejor aún, crea un archivo llamado requirements.txt en el directorio tarea_de_seguridad. La idea ahí es que puedes llevar todas las dependencias del proyecto en ese archivo y sólo hay que ejecutar `pip install -r requirements.txt`. Más información aquí: https://pip.pypa.io/en/latest/user_guide.html#requirements-files

Cuando termines y hagas tu commit, incluye al final del mensaje la frase: `Closes #1`. Con eso este ticket se cierra solo al momento de hacer push.

Saludos,

**Comment by aibsen** [comment]
Hola profesor,
Gracias por sus comentarios! Vamos a subir al git el archivo
requirements.txt a la brevedad.
Saludos

**Comment by injcristianrojas** [comment]
Muevan el requirements.txt al directorio tarea_de_seguridad y estamos.
